name: expire_it
description: App will expire or the user will not able to user after expiry date finishes. Best for freelancing client trial builds.
version: 0.2.0
homepage: https://github.com/raysummee/expire_it
repository: https://github.com/raysummee/expire_it

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ntp: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
